server:
  port: 0 # 用户服务的端口号

spring:
  application:
    name: service-image # 服务名
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s

  config:
    import:
      - "configserver:"
