mail:
  server:
    host: smtp.example.com  # 邮件服务器地址
    port: 587               # 邮件服务器端口
    username: your_email@example.com  # 发送邮件的账号
    password: your_secure_password_or_token  # 发送邮件的密码（建议使用环境变量管理）
  smtp:
    auth: true      # 是否需要认证
    ssl:
      enable: true  # 是否启用 SSL
    starttls:
      enable: false # 是否启用 STARTTLS
