spring:
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: 123456
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          max-active: 200  # 最大连接数
          max-wait: 500ms  # 最大等待时间
          max-idle: 10     # 最大空闲连接数
          min-idle: 5      # 最小空闲连接数