server:
  port: 8761

spring:
  application:
    name: service-infrastructure
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
    service-registry:
      auto-registration:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
